# Generated by Django 5.2.6 on 2025-11-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='duration_days',
            field=models.IntegerField(blank=True, help_text='Duration of habit challenge in days (e.g., 30-day challenge)', null=True),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('missed', 'Missed'), ('none', 'None'), ('skipped', 'Skipped'), ('failed', 'Failed'), ('partial', 'Partial')], default='none', max_length=10),
        ),
    ]
