# Generated by Django 5.2.6 on 2025-11-28 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_habit_duration_days_alter_habitlog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'friends',
                'indexes': [models.Index(fields=['user', 'status'], name='friends_user_id_71f36d_idx'), models.Index(fields=['friend', 'status'], name='friends_friend__1f35fd_idx'), models.Index(fields=['user', 'friend'], name='friends_user_id_020709_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('user', models.F('friend')), _negated=True), name='no_self_friend')],
                'unique_together': {('user', 'friend')},
            },
        ),
    ]
