# Generated by Django 4.2.7 on 2025-12-04 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_character',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='unlocked_characters',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='user',
            name='leaf_dollars',
            field=models.IntegerField(default=50),
        ),
    ]
