# Generated by Django 4.2.7 on 2025-12-04 19:39

from django.db import migrations


def set_all_leaf_dollars_150(apps, schema_editor):
    """Set all existing users' leaf dollars to 150"""
    User = apps.get_model('api', 'User')
    User.objects.all().update(leaf_dollars=150)


def reverse_migration(apps, schema_editor):
    """Reverse: set back to 50 (original default)"""
    User = apps.get_model('api', 'User')
    User.objects.all().update(leaf_dollars=50)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_character_fields'),
    ]

    operations = [
        migrations.RunPython(set_all_leaf_dollars_150, reverse_migration),
    ]
